<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="7762" started-at="2020-10-15T06:53:24Z" finished-at="2020-10-15T06:53:32Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="7762" started-at="2020-10-15T06:53:24Z" finished-at="2020-10-15T06:53:32Z">
      <class name="PracticeMaven.Main">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:PracticeMaven.Main@4439f31e]" name="beforeTest" is-config="true" duration-ms="5373" started-at="2020-10-15T13:53:24Z" finished-at="2020-10-15T13:53:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="run()[pri:0, instance:PracticeMaven.Main@4439f31e]" name="run" duration-ms="1531" started-at="2020-10-15T13:53:29Z" finished-at="2020-10-15T13:53:31Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at PracticeMaven.CommonMethod.visibilityElement(CommonMethod.java:29)
	at PracticeMaven.GoogleAdvancedSearch.checkResults(GoogleAdvancedSearch.java:22)
	at PracticeMaven.Main.run(Main.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- run -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:PracticeMaven.Main@4439f31e]" name="afterTest" is-config="true" duration-ms="841" started-at="2020-10-15T13:53:31Z" finished-at="2020-10-15T13:53:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- PracticeMaven.Main -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
